image: node:latest

stages:
  - build
  

build:
  stage: build
  image: node
  script: 
    - echo "Start building App"
    - cd web-store
    - npm install
    - npm build
    - echo "Build successfully!"





    
