image: node:latest

stages:
  - build
  - docker
  - test
  

build:
  stage: build
  image: node
  script: 
    - echo "Start building App"
    - cd web-store
    - npm install
    - npm build
    - echo "Build successfully!"



test:
  stage: test
  image: node
  script:
    - cd web-store
    - echo "Testing App"
    - npm install
    - npm run cypress:ci
    - echo "Test successfully!"


    
